[theme]
primaryColor = "#0097b2"
backgroundColor = "#b1dbe4"
secondaryBackgroundColor = "#45a1aa"
textColor = "#1e3a5f"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
